### ISSUE TITLE
Implement .validate() method

### ISSUE THREAD

**Issue by andrei-assa** [andrei-assa/arctic-analytics-data-validation#2]
## Data Validation

Implement `.validate()` method using the logic in the referenced code fragment.

https://github.com/andrei-assa/arctic-analytics-data-validation/blob/34ac39de58e1f7a96d96cf600504a768d4a01395/validator/validator.py#L75-L87

**Comment by tashakim** [comment]
Extended what you had in most recent commit (`dev` branch) - 'Progress on DataValidator' hash# 1ef5a66ecb2eb0278e140a4e3da9f95e6d8f266b. Please check if it is ok

**Comment by hardeepkumar9191** [comment]
Issue is fixed.
